Add Player Join Event logic
harding-capstone/server pull request #1
Opened 2019-03-29 21:59 UTC by ajarrett29

@ShepherdJerred did I miss anything?

# Changes Made
added player join event
# Testing Done

2019-03-29 22:13 UTC, ajarrett29 commented
I am fixing conflicts

2019-03-30 01:34 UTC, shepherdjerred requested changes

2019-03-30 01:34 UTC, ShepherdJerred commented on src/main/java/com/shepherdjerred/capstone/server/events/events/PlayerJoinEvent.java
> +  private final ClientId clientId;
A ClientId probably doesn't belong here, but it's not worth the work to find a better design.

2019-03-30 01:34 UTC, ShepherdJerred commented on src/main/java/com/shepherdjerred/capstone/server/events/handlers/PlayerJoinEventHandler.java
> +    connectorHub.sendPacket(new PlayerDescriptionPacket(playerJoinEvent.getPlayer().getName()) {
Don't see a player description packet, create a new packet type called PlayerJoined (or something similar). Our clients need the entire player object, not just the name.

2019-03-30 01:35 UTC, ShepherdJerred commented
Just fix the PlayerJoinEventHandler and then we can merge it in. It looks good!

2019-03-30 15:05 UTC, ajarrett29 commented
@ShepherdJerred I made the changes. Take a look.

2019-03-30 17:56 UTC, shepherdjerred requested changes

2019-03-30 17:56 UTC, ShepherdJerred commented on src/main/java/com/shepherdjerred/capstone/server/events/handlers/PlayerJoinEventHandler.java
> +    connectorHub.sendPacket(new PlayerJoinedPacket(playerJoinEvent.getPlayer()) {
Perfect!

2019-03-30 18:01 UTC, ShepherdJerred commented
Sorry I didn't put this in the last review, but there's one more problem. The client won't know what element to send (because they won't know what elements are taken when joining a lobby). For now just leave it hardcoded.

2019-03-30 21:43 UTC, ShepherdJerred commented
Looks good!

2019-03-30 21:43 UTC, merged