Add Player To Lobby
harding-capstone/server pull request #2
Opened 2019-04-01 23:25 UTC by ajarrett29

# Changes Made
Add player to lobby
# Testing Done

2019-04-02 05:22 UTC, shepherdjerred requested changes

2019-04-02 05:22 UTC, ShepherdJerred commented on src/main/java/com/shepherdjerred/capstone/server/GameServer.java
> +    if (!lobby.isFull()) {
Throw an exception if the lobby is full

2019-04-03 00:10 UTC, ajarrett29 commented
I am new to java exceptions and I really haven't used exceptions much in general.  Let me know what you think.

2019-04-04 00:53 UTC, shepherdjerred approved these changes

2019-04-04 00:53 UTC, ShepherdJerred commented
Merge it once your changes in common are made.

2019-04-04 00:54 UTC, ShepherdJerred commented
Also, the build is failing because there's a test I made that runs infinitely. You might want to disable it haha.

2019-04-07 17:19 UTC, shepherdjerred approved these changes

2019-04-08 17:08 UTC, merged